name: matex

packages:
  - packages/*

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  test:
    exec: flutter test
    packageFilters:
      scope:
        - matex_data
        - matex_financial

  check:dependencies:
    exec: python3 $PWD/scripts/check_dependencies.py
  update:analysis_options:
    exec: $PWD/scripts/update_analysis_options.sh
  sort:imports:
    exec: flutter pub run import_sorter:main

  update:meta:countries:
    exec: python3 $PWD/scripts/data/update_countries.py
    packageFilters:
      scope:
        - matex_data

  update:meta:instruments:
    exec: python3 $PWD/scripts/data/update_instruments.py
    packageFilters:
      scope:
        - matex_data
  update:meta:pairs:
    exec: python3 $PWD/scripts/data/update_pairs.py
    packageFilters:
      scope:
        - matex_data

  update:dependencies:
    exec: python3 $PWD/scripts/update_pubspec.py
