name: matex_financial
description: An assortment of helpful tools and calculators specifically designed for use within the financial sector.
version: 0.0.16
repository: https://github.com/tyrcord/matex/tree/main/packages/financial

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  decimal: ^2.3.3
  pdf: ^3.10.4
  cross_file: ^0.3.3+4
  printing: ^5.11.0
  easy_localization: ^3.0.2

  # MateX
  matex_dart: ^0.11.1
  matex_core: ^0.0.11

  # T
  tbloc: ^0.21.3+2
  t_helpers: ^0.0.28
  tmodel: ^0.5.7

  # Lingua
  lingua_finance: ^0.0.14
  lingua_finance_stock: ^0.0.5
  lingua_core: ^0.0.22
  lingua_settings: ^0.0.10

  # Fastyle
  fastyle_forms: ^0.0.17
  fastyle_core: ^0.0.13
  fastyle_financial: ^0.0.15
  fastyle_calculator: ^1.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.6
  tstore: ^0.8.14
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.2
