name: matex_financial
description: An assortment of helpful tools and calculators specifically designed for use within the financial sector.
version: 0.0.10
repository: https://github.com/tyrcord/matex/tree/main/packages/financial

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.3
  tmodel_dart: ">=0.5.0 <1.0.0"
  matex_core: ^0.0.6
  fastyle_calculator: ^1.17.0
  t_helpers: ">=0.0.21"
  pdf: ^3.10.4
  cross_file: ^0.3.3+4
  printing: ^5.11.0
  fastyle_forms: ^0.0.11
  fastyle_core: ^0.0.6
  fastyle_financial: ^0.0.9
  matex_dart: ^0.11.1
  tbloc: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.6
  tstore: ^0.8.9
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.2
