dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.4+1
  easy_localization: ^3.0.7
  fastyle_buttons: ^0.0.33
  fastyle_calculator: ^1.66.0
  fastyle_core: ^0.0.59
  fastyle_financial: ^0.0.50
  fastyle_forms: ^0.0.54
  fastyle_images: ^0.0.54
  fastyle_settings: ^0.0.59
  flutter:
    sdk: flutter
  lingua_core: ^0.0.45
  lingua_countries: ^0.0.16
  lingua_finance: ^0.0.42
  lingua_finance_dividend: ^0.0.19
  lingua_finance_forex: ^0.0.22
  lingua_finance_instrument: ^0.0.19
  lingua_finance_stock: ^0.0.22
  lingua_number: ^0.0.21
  lingua_settings: ^0.0.26
  lingua_units: ^0.0.19
  matex_core: ^0.0.49
  matex_data: ^0.0.40
  pdf: ^3.11.1
  printing: ^5.13.1
  rxdart: ^0.28.0
  t_helpers: ^0.0.59
  tbloc: ^0.25.2
  tenhance: ^0.0.15
  tlogger: ^0.0.16
  tmodel: ^0.5.19
  tstore: ^0.8.30
description:
  An assortment of helpful tools and calculators specifically designed
  for use within the financial sector.
dev_dependencies:
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: ">=3.24.0"
  sdk: ">=3.5.0 <4.0.0"
name: matex_financial
repository: https://github.com/tyrcord/matex/tree/main/packages/financial
version: 0.0.59
