name: matex_financial
description: An assortment of helpful tools and calculators specifically designed for use within the financial sector.
version: 0.0.29
repository: https://github.com/tyrcord/matex/tree/main/packages/financial

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  decimal: ^2.3.3
  pdf: ^3.10.6
  cross_file: ^0.3.3+6
  printing: ^5.11.1
  easy_localization: ^3.0.3
  rxdart: ^0.27.7

  # MateX
  matex_core: ^0.0.23
  matex_data: ^0.0.17

  # T
  tbloc: ^0.21.8
  t_helpers: ^0.0.42
  tmodel: ^0.5.12
  tstore: ^0.8.21

  # Lingua
  lingua_finance: ^0.0.23
  lingua_finance_stock: ^0.0.8
  lingua_core: ^0.0.32
  lingua_settings: ^0.0.13
  lingua_finance_forex: ^0.0.6
  lingua_units: ^0.0.7

  # Fastyle
  fastyle_forms: ^0.0.35
  fastyle_core: ^0.0.36+1
  fastyle_calculator: ^1.46.0
  fastyle_financial: ^0.0.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.3
