name: matex_financial
description: An assortment of helpful tools and calculators specifically designed for use within the financial sector.
version: 0.0.5+1
repository: https://github.com/tyrcord/matex/tree/main/packages/financial

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.2
  tmodel_dart: ">=0.5.0 <1.0.0"
  matex_core: ^0.0.4
  fastyle_calculator: ">=1.11.0 <2.0.0"
  t_helpers: ">=0.0.15 <1.0.0"
  pdf: ^3.10.4
  cross_file: ^0.3.3+4
  printing: ^5.11.0
  fastyle_forms: ">=0.0.5 <1.0.0"
  fastyle_dart: ^1.2.4
  fastyle_financial: ^0.0.3
  matex_dart: ^0.11.1
  tbloc: ">=0.20.5 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.4
  tstore: ">=0.8.8+1 <1.0.0"
  import_sorter: ^4.6.0
