dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.3+8
  easy_localization: ^3.0.7
  fastyle_buttons: ^0.0.29
  fastyle_calculator: ^1.62.0
  fastyle_core: ^0.0.52
  fastyle_financial: ^0.0.46
  fastyle_forms: ^0.0.50
  fastyle_images: ^0.0.50
  fastyle_settings: ^0.0.55
  flutter:
    sdk: flutter
  lingua_core: ^0.0.40
  lingua_countries: ^0.0.11
  lingua_finance: ^0.0.37
  lingua_finance_dividend: ^0.0.14
  lingua_finance_forex: ^0.0.17
  lingua_finance_instrument: ^0.0.14
  lingua_finance_stock: ^0.0.17
  lingua_number: ^0.0.16
  lingua_settings: ^0.0.21
  lingua_units: ^0.0.13
  matex_core: ^0.0.45
  matex_data: ^0.0.37
  pdf: ^3.10.7
  printing: ^5.11.1
  rxdart: ^0.27.7
  t_helpers: ^0.0.55
  tbloc: ^0.24.0
  tenhance: ^0.0.11
  tlogger: ^0.0.12
  tmodel: ^0.5.15
  tstore: ^0.8.26
description:
  An assortment of helpful tools and calculators specifically designed
  for use within the financial sector.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: ">=3.16.0"
  sdk: ">=3.2.0 <4.0.0"
name: matex_financial
repository: https://github.com/tyrcord/matex/tree/main/packages/financial
version: 0.0.55
