dependencies:
  cross_file: ^0.3.3+8
  easy_localization: ^3.0.4
  fastyle_calculator: ^1.61.0
  fastyle_core: ^0.0.51
  fastyle_financial: ^0.0.45
  fastyle_forms: ^0.0.49
  fastyle_images: ^0.0.49
  fastyle_buttons: ^0.0.28
  fastyle_settings: ^0.0.54
  flutter:
    sdk: flutter
  lingua_core: ^0.0.38
  lingua_finance: ^0.0.35
  lingua_finance_dividend: ^0.0.12
  lingua_finance_forex: ^0.0.15
  lingua_finance_stock: ^0.0.15
  lingua_finance_instrument: ^0.0.12
  lingua_countries: ^0.0.9
  lingua_number: ^0.0.14
  lingua_settings: ^0.0.19
  lingua_units: ^0.0.11
  matex_core: ^0.0.43
  matex_data: ^0.0.35
  pdf: ^3.10.7
  collection: ^1.18.0
  printing: ^5.11.1
  rxdart: ^0.27.7
  t_helpers: ^0.0.52
  tbloc: ^0.22.1+1
  tenhance: ^0.0.8+2
  tlogger: ^0.0.10+1
  tmodel: ^0.5.13+2
  tstore: ^0.8.24+1
description:
  An assortment of helpful tools and calculators specifically designed
  for use within the financial sector.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: ">=3.16.0"
  sdk: ">=3.2.0 <4.0.0"
name: matex_financial
repository: https://github.com/tyrcord/matex/tree/main/packages/financial
version: 0.0.53+2
