dependencies:
  cross_file: ^0.3.3+6
  decimal: ^2.3.3
  easy_localization: ^3.0.3
  fastyle_calculator: ^1.53.0
  fastyle_core: ^0.0.44
  fastyle_financial: ^0.0.38
  fastyle_forms: ^0.0.42
  flutter:
    sdk: flutter
  lingua_core: ^0.0.33
  lingua_finance: ^0.0.29
  lingua_finance_dividend: ^0.0.8
  lingua_finance_forex: ^0.0.11
  lingua_finance_stock: ^0.0.11
  lingua_number: ^0.0.10+1
  lingua_settings: ^0.0.14
  lingua_units: ^0.0.7
  matex_core: ^0.0.28
  matex_data: ^0.0.22
  pdf: ^3.10.6
  printing: ^5.11.1
  rxdart: ^0.27.7
  t_helpers: ^0.0.49+2
  tbloc: ^0.21.8+12
  tenhance: ^0.0.6
  tlogger: ^0.0.7+3
  tmodel: ^0.5.12+12
  tstore: ^0.8.22+7
description:
  An assortment of helpful tools and calculators specifically designed
  for use within the financial sector.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: ">=3.16.0"
  sdk: ">=3.2.0 <4.0.0"
name: matex_financial
repository: https://github.com/tyrcord/matex/tree/main/packages/financial
version: 0.0.38
