dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.4+1
  easy_localization: ^3.0.5
  fastyle_buttons: ^0.0.30
  fastyle_calculator: ^1.63.0
  fastyle_core: ^0.0.53
  fastyle_financial: ^0.0.47
  fastyle_forms: ^0.0.51
  fastyle_images: ^0.0.51
  fastyle_settings: ^0.0.56
  flutter:
    sdk: flutter
  lingua_core: ^0.0.42
  lingua_countries: ^0.0.13
  lingua_finance: ^0.0.39
  lingua_finance_dividend: ^0.0.16
  lingua_finance_forex: ^0.0.19
  lingua_finance_instrument: ^0.0.16
  lingua_finance_stock: ^0.0.19
  lingua_number: ^0.0.18
  lingua_settings: ^0.0.23
  lingua_units: ^0.0.15
  matex_core: ^0.0.46
  matex_data: ^0.0.38
  pdf: ^3.10.8
  printing: ^5.11.1
  rxdart: ^0.27.7
  t_helpers: ^0.0.56
  tbloc: ^0.24.1
  tenhance: ^0.0.12
  tlogger: ^0.0.13
  tmodel: ^0.5.16
  tstore: ^0.8.27
description: An assortment of helpful tools and calculators specifically designed
  for use within the financial sector.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
name: matex_financial
repository: https://github.com/tyrcord/matex/tree/main/packages/financial
version: 0.0.56
