name: matex_core
description: The core tool of the Matex packages.
version: 0.0.22
repository: https://github.com/tyrcord/matex/tree/main/packages/core

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  decimal: ^2.3.3
  collection: ^1.18.0
  share_plus: ^7.2.1
  intl: ^0.18.1
  easy_localization: ^3.0.3

  # T
  tstore: ^0.8.21
  tbloc: ^0.21.8
  t_helpers: ^0.0.42
  tmodel: ^0.5.12

  # Lingua
  lingua_core: ^0.0.31
  lingua_calculator: ^0.0.4

  # Fastyle
  fastyle_settings: ^0.0.39
  fastyle_core: ^0.0.36
  fastyle_calculator: ^1.44.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.3
