dependencies:
  collection: ^1.18.0
  decimal: ^2.3.3
  easy_localization: ^3.0.3
  fastyle_calculator: ^1.55.0
  fastyle_core: ^0.0.46
  fastyle_settings: ^0.0.49
  flutter:
    sdk: flutter
  intl: ^0.18.1
  lingua_calculator: ^0.0.6
  lingua_core: ^0.0.34
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  t_helpers: ^0.0.50
  tbloc: ^0.21.9
  tenhance: ^0.0.7
  tmodel: ^0.5.12+13
  tstore: ^0.8.22+8
description: The core tool of the Matex packages.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
name: matex_core
repository: https://github.com/tyrcord/matex/tree/main/packages/core
version: 0.0.36
