name: matex_core
description: The core tool of the Matex packages.
version: 0.0.11
repository: https://github.com/tyrcord/matex/tree/main/packages/core

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  decimal: ^2.3.3
  collection: ^1.17.1
  share_plus: ^7.1.0
  intl: ^0.18.0
  easy_localization: ^3.0.2

  # T
  tstore: ^0.8.14
  tbloc: ^0.21.3+2
  t_helpers: ^0.0.28
  tmodel: ^0.5.7

  # Lingua
  lingua_core: ^0.0.22
  lingua_calculator: ^0.0.2+1

  # Fastyle
  fastyle_settings: ^0.0.22
  fastyle_core: ^0.0.13
  fastyle_calculator: ^1.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.6
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.2
