dependencies:
  collection: ^1.18.0
  easy_localization: ^3.0.4
  fastyle_calculator: ^1.61.1
  fastyle_core: ^0.0.51+1
  fastyle_settings: ^0.0.54+1
  flutter:
    sdk: flutter
  intl: ^0.18.1
  lingua_calculator: ^0.0.10
  lingua_core: ^0.0.38
  path_provider: ^2.1.1
  share_plus: ^7.2.2
  t_helpers: ^0.0.52
  tbloc: ^0.22.1+1
  tenhance: ^0.0.8+2
  tmodel: ^0.5.13+2
  tstore: ^0.8.24+1
description: The core tool of the Matex packages.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
name: matex_core
repository: https://github.com/tyrcord/matex/tree/main/packages/core
version: 0.0.44
