name: matex_core
description: The core tool of the Matex packages.
version: 0.0.17
repository: https://github.com/tyrcord/matex/tree/main/packages/core

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  decimal: ^2.3.3
  collection: ^1.17.2
  share_plus: ^7.2.1
  intl: ^0.18.1
  easy_localization: ^3.0.3

  # T
  tstore: ^0.8.17
  tbloc: ^0.21.5+2
  t_helpers: ^0.0.32
  tmodel: ^0.5.9+2

  # Lingua
  lingua_core: ^0.0.30
  lingua_calculator: ^0.0.3

  # Fastyle
  fastyle_settings: ^0.0.29
  fastyle_core: ^0.0.24
  fastyle_calculator: ^1.34.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.3
