dependencies:
  collection: ^1.18.0
  easy_localization: ^3.0.4
  fastyle_calculator: ^1.62.0
  fastyle_core: ^0.0.52
  fastyle_settings: ^0.0.55
  flutter:
    sdk: flutter
  intl: ^0.18.1
  lingua_calculator: ^0.0.12
  lingua_core: ^0.0.40
  path_provider: ^2.1.1
  share_plus: ^7.2.2
  t_helpers: ^0.0.55
  tbloc: ^0.24.0
  tenhance: ^0.0.11
  tmodel: ^0.5.15
  tstore: ^0.8.26
description: The core tool of the Matex packages.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
name: matex_core
repository: https://github.com/tyrcord/matex/tree/main/packages/core
version: 0.0.45
