dependencies:
  collection: ^1.18.0
  easy_localization: ^3.0.5
  fastyle_calculator: ^1.63.0
  fastyle_core: ^0.0.53
  fastyle_settings: ^0.0.56
  flutter:
    sdk: flutter
  intl: ^0.19.0
  lingua_calculator: ^0.0.14
  lingua_core: ^0.0.42
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  t_helpers: ^0.0.56
  tbloc: ^0.24.1
  tenhance: ^0.0.12
  tmodel: ^0.5.16
  tstore: ^0.8.27
description: The core tool of the Matex packages.
dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
name: matex_core
repository: https://github.com/tyrcord/matex/tree/main/packages/core
version: 0.0.45
