name: matex_core
description: The core tool of the Matex packages.
version: 0.0.8
repository: https://github.com/tyrcord/matex/tree/main/packages/core

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.3
  tmodel_dart: ^0.5.0
  fastyle_core: ^0.0.8
  fastyle_calculator: ^1.20.0
  tstore: ^0.8.10
  collection: ^1.17.1
  tbloc: ^0.21.1
  t_helpers: ^0.0.25
  share_plus: ^7.1.0
  fastyle_settings: ^0.0.17
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.6
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.2
