name: matex_core
description: The core tool of the Matex packages.
version: 0.0.2
repository: https://github.com/tyrcord/matex/tree/main/packages/core

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.2
  tmodel_dart: ">=0.5.0 <1.0.0"
  fastyle_calculator: ">=1.7.1 <2.0.0"
  fastyle_dart: ">=1.2.3 <2.0.0"
  tstore: ">=0.8.8+1 <1.0.0"
  collection: ^1.17.1
  tbloc: ^0.20.5
  t_helpers: ">=0.0.11 <1.0.0"
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.4
  import_sorter: ^4.6.0
